# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_kartbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartbody',
            name='ability_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kartbody',
            name='body_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
