# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('model_code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('model_type', models.CharField(max_length=10)),
                ('text_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('model_code', models.CharField(max_length=10)),
                ('model_type', models.CharField(max_length=10)),
                ('re_code', models.CharField(max_length=10)),
                ('text_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='kartbody',
            name='ability_img',
        ),
        migrations.RemoveField(
            model_name='kartbody',
            name='author',
        ),
        migrations.AddField(
            model_name='kartbody',
            name='kart_class',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kartbody',
            name='kart_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kartbody',
            name='kart_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
