# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180128_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kartbody',
            old_name='histpry_text',
            new_name='history_text',
        ),
        migrations.RemoveField(
            model_name='apraisal',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='apraisal',
            name='text_code',
        ),
    ]
