# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180205_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('model_code', models.CharField(max_length=10)),
                ('model_type', models.CharField(max_length=10)),
                ('re_code', models.CharField(max_length=10)),
                ('text_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
