# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180207_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apraisal',
            new_name='Appraisal',
        ),
    ]
