# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='model_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appr', to='blog.Kartbody'),
        ),
    ]
