# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180208_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='user_id',
            new_name='title',
        ),
    ]
