# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180208_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='title',
            new_name='user_id',
        ),
    ]
